//
// Created by marttom on 28.10.2019.
//

#ifndef SRC_PLANET_H
#define SRC_PLANET_H


#include "SpaceObject.h"
#include <SFML/Graphics.hpp>

class Planet : public SpaceObject {
private:
    int m_autoGeneratedLifePointPerSecond = 0;
public:
    void AbstractMemberFunction();
    Planet (int autoGeneratedLifePoint, int lifePoint, float x, float y, float scale, int width);

    void generateLifePoint();

    void setAutoGeneratedLifePoint (int number);
};


#endif //SRC_PLANET_H
