//
// Created by marttom on 28.10.2019.
//

#include "Planet.h"

Planet::Planet(int autoGeneratedLifePoint, int lifePoint, float x, float y, float scale, int width) : SpaceObject (lifePoint, x, y, scale, width) {
    auto* texture = new sf::Texture();
    texture->loadFromFile("C:/Users/marttom/Documents/GitHub/2019-JCO-BITPLANETS/src/src/texture/planet.png");
    SpaceObject::setSprite(texture);
}

void Planet::generateLifePoint() {
    SpaceObject::addLifePoint(m_autoGeneratedLifePointPerSecond);
}

void Planet::setAutoGeneratedLifePoint(int number) {
    if (number > 0) {
        m_autoGeneratedLifePointPerSecond = number;
    }
}

void Planet::AbstractMemberFunction() {
}
